controllers:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  test_controller:
    type: TestController

  test_controller2:
    type: legged/TestController2

